### ISSUE TITLE
请问能否自定义point数?

### ISSUE THREAD

**Issue by nongguangneng** [yociduo/scrum-planning-poker#3]
目前的card中只有可选的point,是否可以自定义？

**Comment by DarrickBM** [comment]
您好，感谢您的反馈。我们会在后续版本中增加该功能。

**Comment by riskgod** [comment]
不是标准的流程不可以随意改变这个数的吗

**Comment by riskgod** [comment]
> 目前的card中只有可选的point,是否可以自定义？

标准流程不是不可以自定义的么

**Comment by nanolikeyou** [comment]
修改utils.js里的key value和对应的图片就可以了，计算时是自动 。

**Comment by yociduo** [comment]
> 修改utils.js里的key value和对应的图片就可以了，计算时是自动 。

卡牌图片现在是写死在小程序端，将来会改成用小程序画卡牌
